/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#362f27", 
        "surface-tint": "#ffb954", 
        "primary-container": "#efa83d", 
        "tertiary-fixed": "#cbe6ff", 
        "surface-bright": "#403830", 
        primary: "#ffc87f", 
        "on-error": "#690005", 
        "secondary-container": "#5d421a", 
        "surface-container-high": "#302921", 
        "on-surface-variant": "#d6c4b0", 
        "surface-variant": "#3b332b", 
        background: "#18120b", 
        "outline-variant": "#514536", 
        "tertiary-fixed-dim": "#8fcdff", 
        "secondary-fixed": "#ffddb4", 
        "primary-fixed-dim": "#ffb954", 
        "on-tertiary-container": "#004c72", 
        "on-tertiary": "#003450", 
        "on-secondary-container": "#d5af7d", 
        "on-background": "#eee0d4", 
        "primary-fixed": "#ffddb4", 
        "on-secondary-fixed-variant": "#5d421a", 
        tertiary: "#a9d7ff", 
        "on-secondary": "#442b05", 
        "on-surface": "#eee0d4", 
        "on-secondary-fixed": "#291800", 
        "surface-container": "#251e17", 
        "on-tertiary-fixed": "#001e30", 
        "tertiary-container": "#68befd", 
        error: "#ffb4ab", 
        "inverse-primary": "#835500", 
        "surface-container-lowest": "#130d07", 
        "on-primary-fixed-variant": "#633f00", 
        "on-primary": "#452b00", 
        secondary: "#e8c08d", 
        "surface-dim": "#18120b", 
        "inverse-surface": "#eee0d4", 
        "on-error-container": "#ffdad6", 
        "secondary-fixed-dim": "#e8c08d", 
        "on-primary-container": "#644000", 
        "error-container": "#93000a", 
        "surface-container-low": "#211a13", 
        "on-primary-fixed": "#291800", 
        surface: "#18120b", 
        "on-tertiary-fixed-variant": "#004b71", 
        outline: "#9e8e7c", 
        "surface-container-highest": "#3b332b"
      },
      borderRadius: {
        DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px"
      },
      spacing: {
        unit: "8px", 
        "section-padding-desktop": "120px", 
        gutter: "24px", 
        "section-padding-mobile": "64px", 
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"], 
        "headline-lg": ["Hanken Grotesk", "sans-serif"], 
        "display-lg": ["Hanken Grotesk", "sans-serif"], 
        "body-lg": ["Manrope", "sans-serif"], 
        "label-bold": ["Hanken Grotesk", "sans-serif"], 
        "headline-md": ["Hanken Grotesk", "sans-serif"], 
        "body-md": ["Manrope", "sans-serif"], 
        headline: ["Hanken Grotesk", "sans-serif"], 
        display: ["Hanken Grotesk", "sans-serif"], 
        body: ["Manrope", "sans-serif"], 
        label: ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", {lineHeight: "1.2", fontWeight: "700"}], 
        "headline-lg": ["40px", {lineHeight: "1.2", fontWeight: "700"}], 
        "display-lg": ["64px", {lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800"}], 
        "body-lg": ["18px", {lineHeight: "1.6", fontWeight: "400"}], 
        "label-bold": ["14px", {lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700"}], 
        "headline-md": ["24px", {lineHeight: "1.3", fontWeight: "600"}], 
        "body-md": ["16px", {lineHeight: "1.6", fontWeight: "400"}]
      }
    },
  },
  plugins: [],
}
